config/routes.rb
Rails.application.routes.draw do
  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_up => "register" }

  resources :posts

  root 'posts#index'

  post 'true/:id', to: 'posts#true_answer', as: :true_answer
  post 'false/:id', to: 'posts#false_answer', as: :false_answer

  get 'random_post', to: 'posts#random', as: :random_post
  get '/users/:id', to: 'users#show', as: :show_user
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_category, dependent: :destroy
  has_many :post, through: :post_category
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :user_answers, dependent: :destroy
  has_many :user, through: :user_answers

  has_many :post_category, dependent: :destroy
  has_many :category, through: :post_category
  
  validates :body, presence: true, length: {maximum: 50},
                    uniqueness: { case_sensitive: false }

  def self.random 
    find(pluck(:id).sample)
  end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  has_many :post 
  has_many :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  before_save { self.email = email.downcase }

  has_many :user_answers, dependent: :destroy
  has_many :post, through: :user_answers

  validates :name, presence: true, length: {maximum: 50},
                    uniqueness: { case_sensitive: false }
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
end

app/models/user_answer.rb
class UserAnswer < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :true_answer, :false_answer]

  # GET /posts
  def index
    @posts = Post.all
    @answers = find_answers(@posts) 
  end

  # GET /posts/1
  def show
    @post = Post.find(params[:id])
    @answers = find_answers([@post])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end
  
  # GET /true_answer
  def true_answer
    answer(true)
  end
  
  # GET /false_answer
  def false_answer
    answer(false)
  end

  # GET /random_post
  def random 
    @post = Post.random
    @answers = find_answers([@post])
  end

  private
    def answer(user_answer)
      @answer = UserAnswer.create(answer: user_answer, user_id: current_user.id, post_id: params[:id].to_i)
      @answer.save
      @current_answer = @post.user_answers.find_by(user_id: current_user.id).answer == @post.answer
    end
    
    def find_answers(posts)
      if user_signed_in?
        answers = Hash.new
        posts.each do |post|
          if (!post.user_answers.find_by(user_id: current_user.id).nil?)
            answers[post.id] = post.user_answers.find_by(user_id: current_user.id).answer == post.answer
          end
        end
        return answers
      end
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:body, :answer, :comment, :link, :rate, :count_favourite)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_contact.html.haml
%h3= "Skontaktuj się: "
%h3= "piotr.skoczylas93[at]gmail.com"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Prawda czy fałsz
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  %body
    %header{:class => "header_position navbar navbar-fixed-top navbar-inverse "}
      %div{:class => "container"}
        = link_to "Prawda czy fałsz", root_path, id: "logo"
        %nav
          %ul{:class => "nav navbar-nav"}
            %li 
              = link_to "Strona główna", posts_path, id: "nav-link"
            /%li 
            /  = link_to "Wybierz kategorię", "#", id: "nav-link"
            %li  
              = link_to "Losuj", random_post_path, id: "nav-link"
            /%li  
            /  = link_to "Ranking", "#", id: "nav-link"
            %li 
              = link_to "Dodaj", new_post_path, id: "nav-link"
            %li
              = link_to "Kontakt", "#", id: "nav-link"
          %ul{:class => "nav navbar-right"}
            %li  
              - if user_signed_in?
                = link_to "Witaj " + current_user.name, show_user_path(current_user), id: "nav-linkb"
              - else
                = link_to "Zaloguj się", new_user_session_path, id: "nav-linkb"
    %div{:class => "center jumbotron homepage standard"} 
      = yield

app/views/posts/_false_answer.html.haml
%h3= "Niestety, to nie jest prawidłowa odpowiedź"

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "Błąd")} uniemożliwia zapisanie postu"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :Fakt
    = f.text_area :body
  .field
    = f.label :Odpowiedź
    = f.check_box :answer
  .field
    = f.label :Komentarz
    = f.text_area :comment
  .field
    = f.label :"Link do źródła"
    = f.url_field :link
  .actions
    = f.submit 'Dodaj post'

app/views/posts/_post.html.haml
- if user_signed_in?
  - if !@answers[post.id].nil?
    - if @answers[post.id] == true
      %h3= "Gratuluję, prawidłowa odpowiedź!"
    - else
      %h3= "Niestety, to nie jest prawidłowa odpowiedź"
  - else
    .answer{:id => "answer#{post.id}"}
      = link_to "Prawda", true_answer_path(post), remote: true, method: "post", type: "button", class: "btn btn-default", style: "background: #57D123; color: black"
      = link_to "Fałsz", false_answer_path(post), remote: true, method: "post", type: "button", class: "btn btn-default", style: "background: #D02121; color: black"
- else
  %h3= "Zaloguj się, aby odpowiedać" 

app/views/posts/_true_answer.html.haml
%h3= "Gratuluję, prawidłowa odpowiedź!"

app/views/posts/false_answer.js.erb
var a = <%= @current_answer %>;
if (a) {
  $('#answer' + <%= j(@post.id.to_s) %>).html("<%= j (render 'true_answer') %>");
} else {
  $('#answer' + <%= j(@post.id.to_s) %>).html("<%= j (render 'false_answer') %>");
}

app/views/posts/index.html.haml
- @posts.each do |post|
  %p= link_to post.body, post_path(post),  id: "body_text", :style => "color: black; background: none "
  %td
  %div{:class => "btn-group", :role => "group"}
    = render 'post', post: post
  %hr{:class => "standard-hr"}

app/views/posts/new.html.haml
%h2 Dodaj fakt (lub kłamstwo)
- if user_signed_in?
  = render 'form'
- else
  %h3= "Aby dodać fakt musisz się zalogować"

= link_to 'Powrót', posts_path

app/views/posts/random.html.haml
%h3= @post.body
%td
= render 'post', post: @post

app/views/posts/show.html.haml
%div{:style => "color: black"}
  %h3= @post.body
%td
= render 'post', post: @post

app/views/posts/true_answer.js.erb
var a = <%= @current_answer %>;
if (a) {
  $('#answer' + <%= j(@post.id.to_s) %>).html("<%= j (render 'true_answer') %>");
} else {
  $('#answer' + <%= j(@post.id.to_s) %>).html("<%= j (render 'false_answer') %>");
}

app/views/users/show.html.haml
%div{:class => "center jumbotron homepage standard"} 
  %h3= link_to "Wyloguj się", destroy_user_session_path, :class => "btn btn-default", method: :delete